player_models:

  #cerebras
  - provider: "cerebras"
    model_id: "llama3.1-8b"
  - provider: "cerebras"
    model_id: "qwen-3-235b-a22b-instruct-2507"

  #groq
  - provider: "groq"
    model_id: "openai/gpt-oss-20b"
  - provider: "groq"
    model_id: "qwen/qwen3-32b"
  - provider: "groq"
    model_id: "meta-llama/llama-4-scout-17b-16e-instruct"

director_models:
  # Самая мощная для генерации сценария (Cerebras Preview)
  - provider: "cerebras"
    model_id: "qwen-3-235b-a22b-instruct-2507"

  # Основной логический центр (Groq)
  - provider: "groq"
    model_id: "openai/gpt-oss-120b"

  # Продвинутая модель для контроля процесса
  - provider: "groq"
    model_id: "meta-llama/llama-4-scout-17b-16e-instruct"

disabled_directors:
  - provider: "cerebras"
    model_id: "llama3.1-8b" # Слишком слабая для Директора по новым меркам

disabled_models:
  - provider: "groq"
    model_id: "llama-3.3-70b-versatile"